transformation:
  hp:
    value: 2.0
    types: Steel
  attack:
    value: 0.9
    types: Fire
  attack_speed:
    value: 1.1
    first_type: Bug
    second_type: Flying
  defence:
    value: 5
    excluded_letter: G
    starts_with: G

pokemon_csv_file_path: classpath:pokemon.csv