server:
  port: 5051

transforming:
  hp:
    value: 2.0
    types: Steel
  attack:
    value: 0.9
    types: Fire
  attack_speed:
    value: 1.1
    first_type: Bug
    second_type: Flying
  defence:
    value: 5
    excluded_letter: G
    starts_with: G

pokemon_csv_file_path: classpath:pokemon.csv

spring:
  datasource:
  url: jdbc:h2:mem:recipe
  #spring.datasource.url=jdbc:h2:file:c:/exercise/recipe
  driverClassName: org.h2.Driver
  username: user
  password: password
  data: classpath:data.sql

  jpa:
  database-platform: org.hibernate.dialect.H2Dialect
  hibernate.ddl-auto: create-drop
  show-sql: true

  h2:
    console:
      enabled: true